from PyQt6.QtWidgets import QApplication, QMainWindow
import sys

from MainWindow import Ui_MainWindow  # Replace 'your_ui_file' with the actual name of your UI file

class MyApp(QMainWindow, Ui_MainWindow):
    def __init__(self):
        super().__init__()
        self.setupUi(self)  # This is generated by pyuic6

if __name__ == "__main__":
    app = QApplication(sys.argv)
    my_app = MyApp()
    my_app.show()
    sys.exit(app.exec())
